# docs at https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyInstaller Build

on:
  workflow_dispatch:
  push:
    tags:
      - v*
      - test-*

permissions:
  contents: read

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            generic-name: linux
            executable-extension: ""
          - os: macos-latest
            generic-name: macos
            executable-extension: ""
          - os: windows-latest
            generic-name: windows
            executable-extension: ".exe"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile b616.py
        pyinstaller --onefile generate_excel.py
        mv dist/b616${{ matrix.executable-extension }} dist/b616-${{ matrix.generic-name }}${{ matrix.executable-extension }}
        mv dist/generate_excel${{ matrix.executable-extension }} dist/generate_excel-${{ matrix.generic-name }}${{ matrix.executable-extension }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/b616-${{ matrix.generic-name }}${{ matrix.executable-extension }}
          dist/generate_excel-${{ matrix.generic-name }}${{ matrix.executable-extension }}
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: ${{ startsWith(github.ref, 'refs/tags/v') }}
        draft: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables-${{ matrix.generic-name }}
        path: dist/*
        retention-days: 7
        overwrite: true
